apiVersion: v1
kind: Service
metadata:
  labels:
    app: teste-deployment
  name: teste-deployment
  namespace: teste
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: teste-deployment
  type: NodePort
status:
  loadBalancer: {}
